### PR TITLE
Alphabetized the Gemfile

### PR DESCRIPTION
**Pull request by vvj5**
Alphabetized Gemfile

### CODE REVIEW

**Comment by jah2488** [comment]
:+1:

**Comment by mlgiardina** [comment]
:+1:

**Comment by vvj5** [comment]
Hope that helps keep things tidy! :)

**Comment by vvj5** [comment]
Take this one, last one had a typo

**Comment by jah2488** [comment]
Now the tests are failing :(

**Comment by jah2488** [comment]
Why are we adding jquery-ui ?

**Comment by jah2488** [comment]
Yay tests are passing!

Still can't cleanly merge though.

**Comment by vvj5** [comment]
Removed all the jqery ui stuff. Was following a rails-cast tutorial on styling the datatables, and it didn't work at all. 

I don't know if this PR should be left to die or what - I have a fresh one that should be more relevant to send up...

**Comment by Graciexia** [comment]
:+1:

**Comment by jah2488** [comment]
@vvj5 Yah lets focus on that other branch as this one doesn't have much in it anymore and the other one is probably more up to date.

**Pull request closed without merging**
